[package]
name = "example"
version = "0.1.0"
authors = ["zolkko <zolkko@gmail.com>"]
edition = "2015"

[lib]
name = "example"
crate-type = ["dylib"]

[dependencies]

[dependencies.cpython]
version = "0.2.1"
default-features = false
features = ["python27-sys", "extension-module-2-7"]

